### ISSUE TITLE
Support generic use of Array.prototype.forEach?

### ISSUE THREAD

**Issue by worstperson** [PiotrDabkowski/Js2Py#17]
Here is the test case:

import js2py
t = r'''[].forEach.call("test", function(ch) { console.log(ch) });'''
js2py.eval_js(t)

Information from the spec:

NOTE The forEach function is intentionally generic; it does not require that its this value be an Array object. Therefore it can be transferred to other kinds of objects for use as a method. Whether the forEach function can be applied successfully to a host object is implementation-dependent.

I'm asking about this because I'm working on the unimplemented functions in prototypes/jsarray.py and this issue is making some of my (pre-submission) tests fail.

**Comment by PiotrDabkowski** [comment]
Fixed. Was more complicated than I though - a problem with String.create. Thank you for pointing it out and also thank you for your work on Array prototype, you can commit your work and I add it to Js2Py so everybody can benefit :)

**Comment by PiotrDabkowski** [comment]
I am not very good at using github so I dont know how to contact you otherwise. I have seen that you made some progress, the code works and looks perfectly, thanks. I have implemented remaining functions to save you work, please submit a pull request and I will add your code (with your code array prototype will be finished)
