### ISSUE TITLE
Stack Overflow on  big functions

### ISSUE THREAD

**Issue by tknorris** [PiotrDabkowski/Js2Py#22]
A friend and I have been looking at js2py to use with some obfuscation js and it works great on smaller functions, but as they get larger, it throws a python stack overflow. Is there anything you could do to fix this? Maybe piece-wise evaluation of the js?

Here's a zip that shows working and non-working examples:
https://dl.dropboxusercontent.com/u/4009618/js2py.zip

**Comment by PiotrDabkowski** [comment]
I think you mean python parser stack overflow. I had the same problem. In general 1 line of JS code translates to 1 line of Python code. Unfortunately quite often JS lines are very long (especially when you compress the file in order to reduce the source code size). These lines result in equally long python lines that python parser cant handle. The solution would be to split long lines into few shorter, it can be done, but currently I don't have enough time to look at this. 

You can try to fix it yourself - modify translating_nodes.py and possibly friendly_nodes.py.

**Comment by PiotrDabkowski** [comment]
Fixed. Longer lines are split and put inside functions and executed when needed. You can modify maximal line length in translating_nodes.py file. Currently 400 characters
