### ISSUE TITLE
Quick question: is there any reason you can think of that this translator would not be an optimal translation path to port JS code to C/C++ using Cython or simuliar?

### ISSUE THREAD

**Issue by mcanthony** [PiotrDabkowski/Js2Py#25]
Setting aside of course web platform features being specifically supported in the translation, could one feasibly think the resultant code should be at least something in the same ballpark as the efficiency of handwritten (by a stupid like me) C/C++?

Everything is focused on C/C++ to JS, but I have an equal (perhaps greater) need for just the opposite.

**Comment by PiotrDabkowski** [comment]
Automatic translation of JS to Python by Js2Py is about 4-7 times slower than manual translation of the same JS code to Python. I have not tried using Cython, but probably it's translation is also less effective than manual translation of the same piece of code. So if you want to translate JS to C/C++ using these 2 tools then you can probably expect that the resulting code will be about 50 times slower than manual translation.

Also probably Cython would not work without modifying Js2Py, because Js2Py is using both stack frames  and implementation details of function (like co_code) which happen to be unsupported by Cython - http://docs.cython.org/src/userguide/limitations.html#cython-limitations .
