### ISSUE TITLE
 How do I get the m3u8 streaming link from this code?

### ISSUE THREAD

**Issue by zoreu** [PiotrDabkowski/Js2Py#279]
How do I get the m3u8 streaming link from this code?

https://raw.githubusercontent.com/zoreu/zoreu.github.io/master/kodi/codigo_pagina.txt

I need the code in python that takes the link .m3u8

**Comment by worstperson** [comment]
I would create stubs for everything until the code ran without crashing. One of your stubbed player functions will receive the url, which you save and retrieve after execution.

**Comment by zoreu** [comment]
> I would create stubs for everything until the code ran without crashing. One of your stubbed player functions will receive the url, which you save and retrieve after execution.

I got it from a website and I don't know how to break the encryption

**Comment by worstperson** [comment]
I understood you're problem, and explained how to solve it. If that's not good enough, reverse the deobfuscation routine and reimplement it in python, same why you handle packers.

Has nothing to do with js2py.

**Comment by worstperson** [comment]
I took the time to reverse your sample:
https://gist.github.com/worstperson/075ca954515cf2175a530d3ba864cb43
With a few more samples of different sizes, you could work out a general function for it.

I tried putting the code through js2py, but it's triggering bugs I need to hunt down and fix.

**Comment by worstperson** [comment]
Turns out it wasn't bugs, just user error. Here is an example of how to handle your sample in js2py:
https://gist.github.com/worstperson/b1cab7bad89f6f4e8cf904d6bb2c961b
As you can see, I provided fake objects that the script references to allow execution to continue. When the player function is called, I set the params aside and retrieve them after execution. This sample didn't need functional dom, it's not always this easy.
