### ISSUE TITLE
Possible bug: unicode encoding

### ISSUE THREAD

**Issue by shirish93** [PiotrDabkowski/Js2Py#37]
Hello,

I tried running js2py on rita.js (https://raw.githubusercontent.com/dhowe/RiTaJS/master/src/rita.js) and got the following error.

```
Traceback (most recent call last):
  File "<pyshell#33>", line 1, in <module>
    lib = js2py.eval_js(l)
  File "..\python-3.4.3\lib\site-packages\js2py-0.35-py3.4.egg\js2py\evaljs.py", line 46, in eval_js
    return e.eval(js)
  File "..\python-3.4.3\lib\site-packages\js2py-0.35-py3.4.egg\js2py\evaljs.py", line 108, in eval
    self.execute(code, use_compilation_plan=use_compilation_plan)
  File "..\python-3.4.3\lib\site-packages\js2py-0.35-py3.4.egg\js2py\evaljs.py", line 97, in execute
    hashkey = hashlib.md5(js).digest()
TypeError: Unicode-objects must be encoded before hashing

```

Would you be able to help me figure the issue out, please? Thanks!

For record, js2py.translate_js works successfully. 

I tried js2py.evaljs.EvalJs and got the following error:

```
context = context.__dict__
AttributeError: 'str' object has no attribute '__dict__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<pyshell#42>", line 1, in <module>
    res = js2py.evaljs.EvalJs(l)
  File "...\python-3.4.3\lib\site-packages\js2py-0.35-py3.4.egg\js2py\evaljs.py", line 76, in __init__
    raise TypeError('context has to be either a dict or have __dict__ attr')
TypeError: context has to be either a dict or have __dict__ 
```

Is there anything I'm doing incorrectly/is my understanding of js2py flawed? I understand the 'use strict' limitation, but I'd figured that wouldn't hinder here...

**Comment by PiotrDabkowski** [comment]
Hey, I fixed an error with eval_js. Just update Js2Py or change evaljs.py line 97 to 

`hashkey = hashlib.md5(js.encode('utf-8').digest()
`
I was able to translate and run rita.js, but it raises following exception:

` ReferenceError: makeClass is not defined
`
This is obviously because makeClass is not defined anywhere in the JavaScript code provided.

**Comment by Lexcon** [comment]
Sorry to have caused this, I guess this applies to py3 which I frankly 
didn't test.

On another note, where does Js2Py stand regarding ECMAScript 6? Browsing 
through the code it looks like some constructs were already provisioned, 
like parsing three dots ... in parameters. Maybe somewhere towards 
summer I can jump in a bit although I need to build up more background 
understanding of the library.

How did you build the parser in the first place, translate one on one 
from esprima code, or build from scratch? How to jump into this?

Robert

**Comment by PiotrDabkowski** [comment]
No problem, I did not test Python 3 either, in fact Python 3 was not supported until recently. 
The first parser was written from scratch and it is inside legacy_translators folder. It did not generate AST, it was generating Python code instantly. Since I did not know anything about parser before and I basically invented it on my own it suffered from poor design and had numerous bugs. To fix that I decided to use esprima.js and that was before esprima provided full support for JS 6. I translated esprima to python manually :) Of course you can just use Js2Py to translate new version of esprima.js to python and enjoy a JS 6 parser (it is present in examples folder) but that would affect performance. So the best option would be to simply modify the manual translation. Unfortunately, to support JS 6 we would have to implement all the extra built in objects and the process is rather boring and time consuming and this is the primary reason why I decided not to support JS 6.

**Comment by shirish93** [comment]
Thanks! I tried running https://raw.githubusercontent.com/dhowe/RiTaJS/master/src/header.js through the program, and I got very strange errors I couldn't parse. Would you be able to look through it, please? (not putting in the error log because it was too long)

**Comment by PiotrDabkowski** [comment]
The error is:
`SyntaxError: Line 129: Unexpected end of input`

No wonder you have this error as the JavaScript code you try to run is invalid. You can try running this header.js with any JavaScript interpreter and you will get the same error. Js2Py cant fix bugs with your javascript code ;)

**Comment by shirish93** [comment]
Thanks! It's supposed to be a reasonably popular library... I guess I'll
open an issue with them now!

Shirish
On Apr 15, 2016 11:39 AM, "Piotr Dabkowski" <notifications@github.com>
wrote:

The error is:
SyntaxError: Line 129: Unexpected end of input

No wonder you have this error as the JavaScript code you try to run is
invalid. You can try running this header.js with any JavaScript interpreter
and you will get the same error. Js2Py cant fix bugs with your javascript
code ;)

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
<https://github.com/PiotrDabkowski/Js2Py/issues/37#issuecomment-210510934>

**Comment by PiotrDabkowski** [comment]
It is not the problem with their library. You have to compile the code to the browser version: https://github.com/dhowe/RiTaJS  look at 'With browserify and npm' section. Afterwards you can run rita. I tested it and it works.

**Comment by PiotrDabkowski** [comment]
But in the main.js put just

`rita = require('rita');
`
instead. Now all the rita objects are under name rita. For exmaple 

`rita.RiTa.tokenize('abc the xyz.')`
