### ISSUE TITLE
Support Python 3.

### ISSUE THREAD

**Issue by dmwyatt** [PiotrDabkowski/Js2Py#6]
I guess the title says it all!  

Any plans on this?

**Comment by PiotrDabkowski** [comment]
I have never used six before and I don't know Python 3 very well. Currently highest priority task for me is to complete Array prototype and implement Date and JSON objects and due to limited time it may not be done until end of September.

**Comment by techdragon** [comment]
I'm taking a shot at this using the `future` library instead of `six`.

**Comment by PiotrDabkowski** [comment]
Good luck! It may be quite hard because I was using Python 2 implementation details

**Comment by techdragon** [comment]
@PiotrDabkowski I'm looking through the code, trying to work out what the right way to run the tests, since it looks like there are some tests, just not a clear way to run them. 

At the moment I'm just trying to get tests/ES5Conform.py to run, I just wanted to check I'm heading in the right direction.

**Comment by PiotrDabkowski** [comment]
tests/ES5Conform.py should run just fine. Just run it and it will print test results

**Comment by techdragon** [comment]
I've made some progress, I'll publish a branch with the work so far. But I think I might need you to give some 'guidance' on how to clean up parts of my 'brute force' approach in order to get past some of the final hurdles.

The bulk of the 'language' issues are fixed in my branch. Its logical issues that are currently causing issues. I get as far as generating the code objects but I'm fairly sure that I may be generating the "wrong" code objects due to, as you pointed out, the changes in python implementation details.

I really want to be able to use this library in a Python 3 static website tool project I've already begun writing, (I'm trying to take the best things from Nikola, Pelican, Docpad, and Flask/Frozen-Flask. Trying to build something thats more of a "content pipeline" instead of a 'markdown renderer'), and more generally it feels like an extremely powerful new tool to enhance Python<->JavaScript interoperability, which I would like to have at my disposal in future Python 3 projects. I'm already contemplating how it could be used in web development contexts like as part of building a web framework handling server side rendering of JavaScript 'includes', or even just to improve reusability in a web app, using modular, importable JS code for things like validation or formatting logic, and being able to reuse them on the server. It could also be interesting to try out in combination along with with some of the more 'pythonic' $foo-script compiles to JavaScript type languages such as RapydScript.

**Comment by PiotrDabkowski** [comment]
Cool, thank you for your interest! You must be aware though that Js2Py is pretty slow - javascript executed using Js2Py is about 100 times slower than the same code executed with V8. 

Sure I can help you making it available for Python 3 just send me your code you wrote so far and I will try to make it work.

**Comment by timofonic** [comment]
Any news?

**Comment by PiotrDabkowski** [comment]
I will try to do that by the end of January.

**Comment by hunt3r** [comment]
:+1: Definitely interested in a Python 3 update.

**Comment by PiotrDabkowski** [comment]
Done guys! Way simpler than I thought, took just one afternoon :)

**Comment by fruehwir** [comment]
This is soo great! You just spared me a _lot_ of headache :) Thank you!!
