### ISSUE TITLE
NotImplementedError: TemplateLiteral is not supported!

### ISSUE THREAD

**Issue by stuaxo** [PiotrDabkowski/Js2Py#94]
I was trying to translate this code -
https://raw.githubusercontent.com/mdn/webgl-examples/gh-pages/tutorial/sample5/webgl-demo.js

Which uses template literals (afaict just for multiline strings).

But js2py isn't happy -
```
NotImplementedError: TemplateLiteral is not supported!
```

**Comment by PiotrDabkowski** [comment]
Template literals are part of ECMA 6 which is not supported by js2py normally. You can use js2py.eval_js6 (see readme). 
Also even if you translate this code you will not be able to run it because see first 2 lines:

    const canvas = document.querySelector('#glcanvas');
    const gl = canvas.getContext('webgl');

They require `document` and `canvas` objects which are only implemented by web browsers.

**Comment by stuaxo** [comment]
I will give it a try - I was just translating with the version on your website.

I don't mind that canvas and webgl won't exist, as I want to manually translate the webgl to pyglet.   For some reason I find the best modern *GL tutorials seem to be WebGL these days.

**Comment by PiotrDabkowski** [comment]
Yep, but bear in mind that Js2Py translated code is very ugly and almost unreadable for humans.
